// packages/color-picker/svelte/ColorPreview.svelte
<script lang="ts">
  import { colorPreviewStyle } from '../core';
  import { useColor } from './context';
  let { class: className = '' }: { class?: string } = $props();
  const color = useColor();
</script>

<output
  class="cp-preview {className}"
  style={colorPreviewStyle($color.value)}
  aria-label="Selected color {$color.value}">{$color.value}</output
>

// packages/color-picker/angular/ColorPreview.ts
import { Component } from '@angular/core';
import { colorPreviewStyle } from '../core';
import { useColor } from './context';
@Component({
  selector: 'cp-preview',
  standalone: true,
  template: `<output
    class="cp-preview"
    [style]="colorPreviewStyle(state().value)"
    [attr.aria-label]="'Selected color ' + state().value"
    >{{ state().value }}</output
  >`,
})
export class ColorPreview {
  readonly colorPreviewStyle = colorPreviewStyle;
  readonly state = useColor();
}
