// packages/color-picker/react/ColorCollection.tsx
'use client';
import { useSyncExternalStore, type ReactNode } from 'react';
import {
  type ColorCollectionClasses,
  type ColorCollectionStore,
} from '../core';
import { useColor, useColorStore } from './context';
/** Recent or favorite colors, using the nearest color context. */
export function ColorCollection({
  collection,
  kind = 'recent',
  label = kind === 'recent' ? 'Recent colors' : 'Favorite colors',
  classes = {},
  renderLabel,
}: {
  collection: ColorCollectionStore;
  kind?: 'recent' | 'favorites';
  label?: string;
  classes?: ColorCollectionClasses;
  renderLabel?: (color: string) => ReactNode;
}) {
  const store = useColorStore(),
    color = useColor();
  const state = useSyncExternalStore(
    collection.subscribe,
    collection.getSnapshot,
    collection.getSnapshot,
  );
  return (
    <fieldset
      className={`cp-collection ${classes.root ?? ''}`}
      disabled={color.disabled}
    >
      <legend className={classes.label}>{label}</legend>
      {state[kind].map((value) => (
        <button
          key={value}
          type="button"
          className={`cp-swatch ${classes.item ?? ''}`}
          style={{ background: value }}
          aria-label={value}
          onClick={() => store.setHex(value)}
        >
          {renderLabel?.(value)}
        </button>
      ))}
    </fieldset>
  );
}

// packages/color-picker/angular/ColorCollection.ts
import {
  Component,
  Input,
  inject,
  signal,
  DestroyRef,
  type OnChanges,
} from '@angular/core';
import { useColorStore } from './context';
import { useColor } from './context';
@Component({
  selector: 'cp-collection',
  standalone: true,
  template: `<fieldset
    [class]="'cp-collection ' + (classes.root || '')"
    [disabled]="color().disabled"
  >
    <legend [class]="classes.label || ''">{{ label }}</legend>
    @for (value of state()[kind]; track value) {
      <button
        type="button"
        [class]="'cp-swatch ' + (classes.item || '')"
        [style.background]="value"
        [attr.aria-label]="value"
        (click)="store.setHex(value)"
      ></button>
    }
  </fieldset>`,
})
export class ColorCollection implements OnChanges {
  @Input({ required: true })
  collection!: import('../core').ColorCollectionStore;
  @Input() kind: 'recent' | 'favorites' = 'recent';
  @Input() label = 'Recent colors';
  @Input() classes: import('../core').ColorCollectionClasses = {};
  readonly store = useColorStore();
  readonly color = useColor();
  readonly state = signal<import('../core').ColorCollectionSnapshot>({
    recent: [],
    favorites: [],
  });
  private unsubscribe?: () => void;
  constructor() {
    inject(DestroyRef).onDestroy(() => this.unsubscribe?.());
  }
  ngOnChanges() {
    this.unsubscribe?.();
    this.state.set(this.collection.getSnapshot());
    this.unsubscribe = this.collection.subscribe(() =>
      this.state.set(this.collection.getSnapshot()),
    );
  }
}
