// packages/color-picker/react/ColorSurface.tsx
'use client';
import { ColorArea } from './ColorArea';
import { ColorSlider } from './ColorSlider';
import { ColorWheel } from './ColorWheel';
import { useColor } from './context';
export function ColorSurface() {
  const state = useColor();
  return (
    <>
      {state.view === 'wheel' ? <ColorWheel /> : <ColorArea />}
      <ColorSlider channel={state.view === 'wheel' ? 'v' : 'h'} />
    </>
  );
}

// packages/color-picker/angular/ColorSurface.ts
import { Component } from '@angular/core';
import { useColor } from './context';
import { ColorArea } from './ColorArea';
import { ColorWheel } from './ColorWheel';
import { ColorSlider } from './ColorSlider';
@Component({
  selector: 'cp-surface',
  standalone: true,
  imports: [ColorArea, ColorWheel, ColorSlider],
  template: `@if (state().view === 'wheel') {
      <cp-wheel />
    } @else {
      <cp-area />
    }
    <cp-slider [channel]="state().view === 'wheel' ? 'v' : 'h'" />`,
})
export class ColorSurface {
  readonly state = useColor();
}
