// packages/color-picker/react/ColorSwatch.tsx
'use client';
import { useColorStore } from './context';
export function ColorSwatch({
  value,
  label = value,
  className = '',
}: {
  value: string;
  label?: string;
  className?: string;
}) {
  const store = useColorStore();
  return (
    <button
      type="button"
      className={`cp-swatch ${className}`}
      aria-label={label}
      style={{ background: value }}
      onClick={() => store.setHex(value)}
    />
  );
}

// packages/color-picker/angular/ColorSwatch.ts
import { Component, Input } from '@angular/core';
import { useColorStore } from './context';
@Component({
  selector: 'cp-swatch',
  standalone: true,
  template: `<button
    type="button"
    class="cp-swatch"
    [attr.aria-label]="label || value"
    [style.background]="value"
    (click)="store.setHex(value)"
  ></button>`,
})
export class ColorSwatch {
  @Input() value = '#6366F1';
  @Input() label = '';
  readonly store = useColorStore();
}
