// packages/color-picker/react/primitives.tsx
'use client';
import { ColorEyeDropper } from './ColorEyeDropper';
import {
  createContext,
  forwardRef,
  useContext,
  useEffect,
  useRef,
  useState,
  type ButtonHTMLAttributes,
  type HTMLAttributes,
  type InputHTMLAttributes,
  type ReactNode,
} from 'react';
import {
  bindColorArea,
  bindColorSlider,
  bindColorValueInput,
  bindMarkerWheel,
  colorInputAttributes,
  createColorStore,
  nextColorFormat,
  sliderAttributes,
  sliderLabels,
  sliderTrackVariables,
  subscribeColor,
  surfaceStyles,
  thumbPosition,
  type ColorFormat,
  type ColorInputOptions,
  type ColorSnapshot,
  type ColorStore,
  type ColorView,
  type HSV,
  type ColorMarker as Marker,
  type SliderChannel,
} from '../core';
import { Context, useColor, useColorStore } from './context';

export interface ColorRootProps {
  store?: ColorStore;
  value?: string;
  defaultValue?: string;
  disabled?: boolean;
  onValueChange?: (value: string) => void;
  children: ReactNode;
}
/** Context only. Arrange its children in any native layout. */
export function ColorRoot({
  store: provided,
  value,
  defaultValue,
  disabled,
  onValueChange,
  children,
}: ColorRootProps) {
  const [store] = useState(() => {
    const initial =
      provided ??
      createColorStore(value ?? defaultValue, 'hex', 'area', disabled);
    if (disabled !== undefined) initial.setDisabled(disabled);
    return initial;
  });
  const latest = useRef(onValueChange);
  latest.current = onValueChange;
  useEffect(() => {
    if (disabled !== undefined) store.setDisabled(disabled);
  }, [store, disabled]);
  useEffect(() => {
    if (value !== undefined) store.setHex(value);
  }, [store, value]);
  useEffect(
    () => subscribeColor(store, (hex) => latest.current?.(hex)),
    [store],
  );
  return <Context.Provider value={store}>{children}</Context.Provider>;
}
const SurfaceContext = createContext<ColorView>('area');
export interface ColorPlaneProps extends Omit<
  HTMLAttributes<HTMLDivElement>,
  'onSelect'
> {
  view?: ColorView;
  markers?: readonly Marker[];
  activeId?: string;
  onSelect?: (id: string) => void;
  onMarkerChange?: (id: string, hsv: Partial<HSV>) => void;
}
function assignRef<T>(ref: React.ForwardedRef<T>, value: T | null) {
  if (typeof ref === 'function') ref(value);
  else if (ref) ref.current = value;
}
/** Only gradients, pointer/keyboard behavior and the geometry context. Children own the thumb. */
export const ColorPlane = forwardRef<HTMLDivElement, ColorPlaneProps>(
  function ColorPlane(
    {
      view = 'area',
      markers,
      activeId,
      onSelect,
      onMarkerChange,
      children,
      style,
      ...attributes
    },
    forwarded,
  ) {
    const store = useColorStore(),
      state = useColor(),
      element = useRef<HTMLDivElement | null>(null);
    const latest = useRef({ markers, activeId, onSelect, onMarkerChange });
    latest.current = { markers, activeId, onSelect, onMarkerChange };
    const multi = markers !== undefined;
    useEffect(
      () =>
        multi
          ? bindMarkerWheel(element.current!, {
              getMarkers: () => latest.current.markers ?? [],
              getActiveId: () =>
                latest.current.activeId ??
                latest.current.markers?.[0]?.id ??
                '',
              select: (id) => latest.current.onSelect?.(id),
              setHSV: (id, hsv) => latest.current.onMarkerChange?.(id, hsv),
            })
          : bindColorArea(element.current!, store, view),
      [store, view, multi],
    );
    return (
      <SurfaceContext.Provider value={view}>
        <div
          role="group"
          aria-label={
            view === 'wheel'
              ? 'Hue and saturation'
              : 'Saturation and brightness'
          }
          {...attributes}
          ref={(node) => {
            element.current = node;
            assignRef(forwarded, node);
          }}
          data-cp-part="surface"
          data-view={view}
          aria-disabled={state.disabled}
          tabIndex={state.disabled ? -1 : (attributes.tabIndex ?? 0)}
          style={{
            ...surfaceStyles(multi ? { ...state, v: 100 } : state, view),
            ...style,
          }}
        >
          {children}
        </div>
      </SurfaceContext.Provider>
    );
  },
);
export const ColorWheelSurface = forwardRef<
  HTMLDivElement,
  Omit<ColorPlaneProps, 'view'>
>(function ColorWheelSurface(props, ref) {
  return <ColorPlane {...props} view="wheel" ref={ref} />;
});
export const ColorThumb = forwardRef<
  HTMLSpanElement,
  HTMLAttributes<HTMLSpanElement>
>(function ColorThumb({ style, ...attributes }, ref) {
  const state = useColor(),
    view = useContext(SurfaceContext);
  return (
    <span
      {...attributes}
      ref={ref}
      data-cp-part="thumb"
      aria-hidden="true"
      style={{ ...thumbPosition(state, view), ...style }}
    />
  );
});
export const ColorMarkerThumb = forwardRef<
  HTMLButtonElement,
  ButtonHTMLAttributes<HTMLButtonElement> & { marker: Marker; active?: boolean }
>(function ColorMarkerThumb(
  { marker, active = false, style, children, disabled, ...attributes },
  ref,
) {
  const state = useColor();
  return (
    <button
      type="button"
      aria-label={marker.ariaLabel ?? marker.id}
      {...attributes}
      ref={ref}
      disabled={disabled || state.disabled}
      data-cp-part="marker"
      data-marker-id={marker.id}
      aria-pressed={active}
      data-state={active ? 'active' : 'inactive'}
      data-small={!marker.label || undefined}
      style={{
        ...thumbPosition(marker.color, 'wheel'),
        pointerEvents: 'auto',
        background: marker.color.hex,
        zIndex: active ? 2 : 1,
        ...style,
      }}
    >
      {children ?? marker.label}
    </button>
  );
});
export const ColorRange = forwardRef<
  HTMLInputElement,
  Omit<InputHTMLAttributes<HTMLInputElement>, 'value' | 'defaultValue'> & {
    channel?: SliderChannel;
  }
>(function ColorRange(
  { channel = 'h', style, disabled, ...attributes },
  forwarded,
) {
  const store = useColorStore(),
    state = useColor(),
    element = useRef<HTMLInputElement | null>(null);
  useEffect(
    () => bindColorSlider(element.current!, store, channel, () => !!disabled),
    [store, channel, disabled],
  );
  return (
    <input
      aria-label={sliderLabels[channel]}
      {...attributes}
      {...sliderAttributes(state, channel)}
      disabled={disabled || state.disabled}
      data-cp-part="slider"
      data-channel={channel}
      ref={(node) => {
        element.current = node;
        assignRef(forwarded, node);
      }}
      style={{ ...sliderTrackVariables(state), ...style }}
      onChange={attributes.onChange ?? (() => {})}
    />
  );
});
export const ColorField = forwardRef<
  HTMLInputElement,
  Omit<InputHTMLAttributes<HTMLInputElement>, 'value' | 'defaultValue'> &
    ColorInputOptions
>(function ColorField({ format, index, disabled, ...attributes }, forwarded) {
  const store = useColorStore(),
    state = useColor(),
    element = useRef<HTMLInputElement | null>(null);
  useEffect(
    () =>
      bindColorValueInput(
        element.current!,
        store,
        { format, index },
        () => !!disabled,
      ),
    [store, format, index, disabled],
  );
  const defaults = colorInputAttributes(state, { format, index });
  return (
    <input
      {...defaults}
      {...attributes}
      defaultValue={defaults.value}
      value={undefined}
      disabled={disabled || state.disabled}
      data-cp-part="input"
      spellCheck={false}
      ref={(node) => {
        element.current = node;
        assignRef(forwarded, node);
      }}
    />
  );
});
export const ColorFormatTrigger = forwardRef<
  HTMLButtonElement,
  ButtonHTMLAttributes<HTMLButtonElement> & {
    format?: ColorFormat;
    render?: (state: ColorSnapshot) => ReactNode;
  }
>(function ColorFormatTrigger(
  { format, render, children, onClick, disabled, ...attributes },
  ref,
) {
  const store = useColorStore(),
    state = useColor();
  return (
    <button
      type="button"
      aria-label="Change color format"
      {...attributes}
      ref={ref}
      disabled={disabled || state.disabled}
      data-cp-part="format-trigger"
      aria-pressed={format ? state.format === format : undefined}
      onClick={(event) => {
        onClick?.(event);
        if (!event.defaultPrevented) nextColorFormat(store, format);
      }}
    >
      {render ? render(state) : (children ?? state.format.toUpperCase())}
    </button>
  );
});
export const ColorPicker = {
  Root: ColorRoot,
  Area: ColorPlane,
  Wheel: ColorWheelSurface,
  Thumb: ColorThumb,
  Marker: ColorMarkerThumb,
  Slider: ColorRange,
  Input: ColorField,
  ChannelInput: ColorField,
  FormatTrigger: ColorFormatTrigger,
  EyeDropper: ColorEyeDropper,
};

// packages/color-picker/angular/primitives.ts
import { ColorEyeDropper } from './ColorEyeDropper';
import {
  Directive,
  Injectable,
  Input,
  Output,
  EventEmitter,
  ElementRef,
  DestroyRef,
  inject,
  afterNextRender,
  type OnInit,
  type OnChanges,
} from '@angular/core';
import { ColorContext, useColor, useColorStore } from './context';
import {
  createColorStore,
  subscribeColor,
  surfaceStyles,
  thumbPosition,
  styleText,
  bindColorSurface,
  bindMarkerWheel,
  bindColorSlider,
  bindColorValueInput,
  colorInputAttributes,
  sliderAttributes,
  sliderLabels,
  sliderTrackVariables,
  nextColorFormat,
  type ColorStore,
  type ColorView,
  type ColorFormat,
  type ColorInputOptions,
  type SliderChannel,
  type ColorMarker,
  type HSV,
} from '../core';
/** Native host with no generated children. */
@Directive({
  selector: '[cpRoot]',
  standalone: true,
  providers: [ColorContext],
  exportAs: 'cpRoot',
})
export class ColorRoot implements OnInit, OnChanges {
  @Input() store?: ColorStore;
  @Input() value?: string;
  @Input() disabled?: boolean;
  @Output() valueChange = new EventEmitter<string>();
  private context = inject(ColorContext);
  private destroy = inject(DestroyRef);
  ngOnInit() {
    this.context.configure(
      this.store ?? createColorStore(this.value, 'hex', 'area', this.disabled),
    );
    if (this.disabled !== undefined)
      this.context.store.setDisabled(this.disabled);
    this.destroy.onDestroy(
      subscribeColor(this.context.store, (value) =>
        this.valueChange.emit(value),
      ),
    );
  }
  ngOnChanges() {
    if (this.value !== undefined) this.context.store.setHex(this.value);
    if (this.disabled !== undefined)
      this.context.store.setDisabled(this.disabled);
  }
}
@Injectable()
export class ColorSurfaceContext {
  view: ColorView = 'area';
}
@Directive({
  selector: '[cpArea],[cpWheel]',
  standalone: true,
  providers: [ColorSurfaceContext],
  exportAs: 'cpSurface',
  host: {
    '[attr.data-cp-part]': '"surface"',
    '[attr.data-view]': 'view',
    '[attr.role]': '"group"',
    '[attr.tabindex]': 'state().disabled ? -1 : 0',
    '[attr.aria-disabled]': 'state().disabled',
    '[style.position]': '"relative"',
    '[style.touch-action]': '"none"',
    '[style.background]': 'styles().background',
    '[style.aspect-ratio]': 'styles().aspectRatio ?? null',
    '[style.border-radius]': 'styles().borderRadius ?? null',
  },
})
export class ColorPlane implements OnChanges {
  @Input() cpMarkers?: readonly ColorMarker[];
  @Input() cpActiveId?: string;
  @Output() markerSelect = new EventEmitter<string>();
  @Output() markerChange = new EventEmitter<{
    id: string;
    hsv: Partial<HSV>;
  }>();
  readonly state = useColor();
  private store = useColorStore();
  private node = inject(ElementRef<HTMLElement>).nativeElement;
  readonly view: ColorView = this.node.hasAttribute('cpWheel')
    ? 'wheel'
    : 'area';
  private ready = false;
  private stop?: () => void;
  private multi?: boolean;
  styles() {
    return surfaceStyles(
      this.cpMarkers ? { ...this.state(), v: 100 } : this.state(),
      this.view,
    );
  }
  constructor() {
    inject(ColorSurfaceContext).view = this.view;
    afterNextRender(() => {
      this.ready = true;
      this.bind();
    });
    inject(DestroyRef).onDestroy(() => this.stop?.());
  }
  ngOnChanges() {
    if (this.ready) this.bind();
  }
  private bind() {
    const multi = this.cpMarkers !== undefined;
    if (this.multi === multi && this.stop) return;
    this.multi = multi;
    this.stop?.();
    this.stop = this.cpMarkers
      ? bindMarkerWheel(this.node, {
          getMarkers: () => this.cpMarkers ?? [],
          getActiveId: () => this.cpActiveId ?? this.cpMarkers?.[0]?.id ?? '',
          select: (id) => this.markerSelect.emit(id),
          setHSV: (id, hsv) => this.markerChange.emit({ id, hsv }),
        })
      : bindColorSurface(this.node, this.store, this.view);
  }
}
@Directive({
  selector: '[cpThumb]',
  standalone: true,
  host: {
    '[attr.data-cp-part]': '"thumb"',
    '[attr.aria-hidden]': '"true"',
    '[style.position]': '"absolute"',
    '[style.transform]': '"translate(-50%,-50%)"',
    '[style.pointer-events]': '"none"',
    '[style.left]': 'position().left',
    '[style.top]': 'position().top',
  },
})
export class ColorThumb {
  private state = useColor();
  private view = inject(ColorSurfaceContext);
  position() {
    return thumbPosition(this.state(), this.view.view);
  }
}
@Directive({
  selector: 'input[cpSlider]',
  standalone: true,
  host: {
    '[attr.type]': '"range"',
    '[attr.min]': '0',
    '[attr.max]': 'cpSlider === "h" ? 359 : 100',
    '[attr.aria-label]': 'ariaLabel ?? labels[cpSlider]',
    '[attr.step]': 'cpSlider === "alpha" ? 0.1 : 1',
    '[attr.data-cp-part]': '"slider"',
    '[attr.data-channel]': 'cpSlider',
    '[disabled]': 'disabled || state().disabled',
    '[value]': 'attrs().value',
    '[style.--cp-alpha-color]': 'state().hex',
    '[style.--cp-saturation-start]': 'variables()["--cp-saturation-start"]',
    '[style.--cp-saturation-end]': 'variables()["--cp-saturation-end"]',
    '[style.--cp-brightness-end]': 'variables()["--cp-brightness-end"]',
  },
})
export class ColorRange implements OnChanges {
  readonly labels = sliderLabels;
  @Input('aria-label') ariaLabel?: string;
  @Input() cpSlider: SliderChannel = 'h';
  @Input() disabled = false;
  readonly state = useColor();
  private store = useColorStore();
  private input = inject(ElementRef<HTMLInputElement>).nativeElement;
  private ready = false;
  private stop?: () => void;
  attrs() {
    return sliderAttributes(this.state(), this.cpSlider);
  }
  variables() {
    return sliderTrackVariables(this.state());
  }
  constructor() {
    afterNextRender(() => {
      this.ready = true;
      this.bind();
    });
    inject(DestroyRef).onDestroy(() => this.stop?.());
  }
  ngOnChanges() {
    if (this.ready) this.bind();
  }
  private bind() {
    this.stop?.();
    this.stop = bindColorSlider(
      this.input,
      this.store,
      this.cpSlider,
      () => this.disabled,
    );
  }
}
@Directive({
  selector: 'input[cpInput]',
  standalone: true,
  host: {
    '[attr.data-cp-part]': '"input"',
    '[attr.type]': 'attrs().type',
    '[attr.aria-label]': 'ariaLabel ?? attrs()["aria-label"]',
    '[attr.value]': 'attrs().value',
    '[attr.min]': 'attrs().min ?? null',
    '[attr.max]': 'attrs().max ?? null',
    '[attr.step]': 'attrs().step ?? null',
    '[disabled]': 'disabled || state().disabled',
  },
})
export class ColorField implements OnChanges {
  @Input('aria-label') ariaLabel?: string;
  @Input() format?: ColorFormat;
  @Input() index?: 0 | 1 | 2;
  @Input() disabled = false;
  readonly state = useColor();
  private store = useColorStore();
  private input = inject(ElementRef<HTMLInputElement>).nativeElement;
  private ready = false;
  private stop?: () => void;
  attrs() {
    return colorInputAttributes(this.state(), {
      format: this.format,
      index: this.index,
    });
  }
  constructor() {
    afterNextRender(() => {
      this.ready = true;
      this.bind();
    });
    inject(DestroyRef).onDestroy(() => this.stop?.());
  }
  ngOnChanges() {
    if (this.ready) this.bind();
    else this.input.value = String(this.attrs().value);
  }
  private bind() {
    this.stop?.();
    this.stop = bindColorValueInput(
      this.input,
      this.store,
      { format: this.format, index: this.index },
      () => this.disabled,
    );
  }
}
@Directive({
  selector: 'button[cpFormatTrigger]',
  standalone: true,
  host: {
    '[attr.type]': '"button"',
    '[attr.data-cp-part]': '"format-trigger"',
    '[disabled]': 'disabled || state().disabled',
    '[attr.aria-pressed]': 'format ? state().format === format : null',
    '(click)': 'change($event)',
  },
})
export class ColorFormatTrigger {
  @Input() format?: ColorFormat;
  @Input() disabled = false;
  readonly state = useColor();
  private store = useColorStore();
  change(event: Event) {
    if (!event.defaultPrevented && !this.disabled)
      nextColorFormat(this.store, this.format);
  }
}
export const colorPickerPrimitives = [
  ColorEyeDropper,
  ColorRoot,
  ColorPlane,
  ColorThumb,
  ColorRange,
  ColorField,
  ColorFormatTrigger,
] as const;
