// packages/color-picker/svelte/ColorEyeDropper.svelte
<script lang="ts">
  import { onMount, type Snippet } from 'svelte';
  import type { HTMLButtonAttributes } from 'svelte/elements';
  import {
    createColorEyeDropper,
    type ColorEyeDropperController,
    type ColorEyeDropperState,
  } from '../core';
  import { useColor, useColorStore } from './context';
  let {
    preserveAlpha = true,
    onPick,
    onPickError,
    children,
    onclick,
    disabled = false,
    ref = $bindable(),
    ...attributes
  }: Omit<HTMLButtonAttributes, 'children'> & {
    preserveAlpha?: boolean;
    onPick?: (hex: string) => void;
    onPickError?: (error: Error) => void;
    children?: Snippet<[ColorEyeDropperState]>;
    ref?: HTMLButtonElement;
  } = $props();
  const color = useColor(),
    store = useColorStore();
  let eye: ColorEyeDropperController | undefined;
  let state = $state<ColorEyeDropperState>({
    supported: false,
    pending: false,
    error: undefined,
  });
  onMount(() => {
    eye = createColorEyeDropper(store);
    const stop = eye.subscribe(() => (state = eye!.getSnapshot()));
    eye.mount();
    return () => {
      stop();
      eye?.destroy();
      eye = undefined;
    };
  });
  $effect(() => {
    if (disabled) eye?.cancel();
  });
</script>

<button
  type="button"
  aria-label="Pick color from screen"
  {...attributes}
  bind:this={ref}
  disabled={disabled || $color.disabled || !state.supported || state.pending}
  data-cp-part="eyedropper"
  data-cp-supported={state.supported}
  aria-busy={state.pending}
  onclick={(event) => {
    onclick?.(event);
    if (event.defaultPrevented || disabled) return;
    void eye
      ?.pick({ preserveAlpha })
      .then((hex) => {
        if (hex) onPick?.(hex);
      })
      .catch((error) => onPickError?.(error));
  }}
>
  {#if children}{@render children(state)}{:else}Pick from screen{/if}
</button>

// packages/color-picker/react/ColorEyeDropper.tsx
'use client';
import {
  forwardRef,
  useEffect,
  useRef,
  useState,
  type ButtonHTMLAttributes,
} from 'react';
import {
  createColorEyeDropper,
  type ColorEyeDropperController,
  type ColorEyeDropperState,
} from '../core';
import { useColor, useColorStore } from './context';
export interface ColorEyeDropperProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  preserveAlpha?: boolean;
  onPick?: (hex: string) => void;
  onPickError?: (error: Error) => void;
  render?: (state: ColorEyeDropperState) => React.ReactNode;
}
export const ColorEyeDropper = forwardRef<
  HTMLButtonElement,
  ColorEyeDropperProps
>(function ColorEyeDropper(
  {
    preserveAlpha = true,
    onPick,
    onPickError,
    render,
    children,
    disabled = false,
    onClick,
    ...attributes
  },
  ref,
) {
  const store = useColorStore(),
    color = useColor(),
    controller = useRef<ColorEyeDropperController>();
  const [state, setState] = useState<ColorEyeDropperState>({
    supported: false,
    pending: false,
    error: undefined,
  });
  useEffect(() => {
    const eye = createColorEyeDropper(store);
    controller.current = eye;
    const stop = eye.subscribe(() => setState(eye.getSnapshot()));
    eye.mount();
    return () => {
      stop();
      eye.destroy();
      controller.current = undefined;
    };
  }, [store]);
  useEffect(() => {
    if (disabled) controller.current?.cancel();
  }, [disabled]);
  return (
    <button
      type="button"
      aria-label="Pick color from screen"
      {...attributes}
      ref={ref}
      disabled={disabled || color.disabled || !state.supported || state.pending}
      data-cp-part="eyedropper"
      data-cp-supported={state.supported}
      aria-busy={state.pending}
      onClick={(event) => {
        onClick?.(event);
        if (event.defaultPrevented || disabled) return;
        void controller.current
          ?.pick({ preserveAlpha })
          .then((hex) => {
            if (hex) onPick?.(hex);
          })
          .catch((error) => onPickError?.(error));
      }}
    >
      {render ? render(state) : (children ?? 'Pick from screen')}
    </button>
  );
});
