// packages/color-picker/angular/ColorInput.ts
import { Component, Input } from '@angular/core';
import {
  type ColorPartClasses,
  type ChannelFormat,
  type ChannelIndex,
  type ColorFormat,
} from '../core';
import { useColor } from './context';
import { ColorTextInput } from './ColorTextInput';
import { ColorChannelInput } from './ColorChannelInput';
@Component({
  selector: 'cp-input',
  standalone: true,
  imports: [ColorTextInput, ColorChannelInput],
  template: `@if (selectedFormat() === 'hex') {
      <cp-text-input
        format="hex"
        [classes]="classes"
        [className]="className"
        [label]="label || 'HEX'"
      />
    } @else {
      <div
        class="cp-channels"
        role="group"
        [attr.aria-label]="label || selectedFormat().toUpperCase()"
      >
        @for (index of indices; track index) {
          <cp-channel-input
            [classes]="classes"
            [className]="className"
            [format]="channelFormat()"
            [index]="index"
          />
        }
      </div>
    }`,
})
export class ColorInput {
  @Input() classes: ColorPartClasses = {};
  @Input() className = '';
  @Input() format?: ColorFormat;
  @Input() label = '';
  readonly state = useColor();
  readonly indices: ChannelIndex[] = [0, 1, 2];
  selectedFormat() {
    return this.format ?? this.state().format;
  }
  channelFormat() {
    return this.selectedFormat() as ChannelFormat;
  }
}

// packages/color-picker/react/ColorInput.tsx
'use client';
import { type ColorFormat, type ColorPartClasses } from '../core';
import { ColorChannelInput } from './ColorChannelInput';
import { ColorTextInput } from './ColorTextInput';
import { useColor } from './context';
export function ColorInput({
  format: override,
  label,
  className = '',
  classes = {},
}: {
  format?: ColorFormat;
  label?: string;
  className?: string;
  classes?: ColorPartClasses;
}) {
  const state = useColor(),
    format = override ?? state.format;
  return format === 'hex' ? (
    <ColorTextInput
      format="hex"
      label={label ?? 'HEX'}
      className={className}
      classes={classes}
    />
  ) : (
    <div
      className={`cp-channels ${className}`}
      role="group"
      aria-label={label ?? format.toUpperCase()}
    >
      {([0, 1, 2] as const).map((index) => (
        <ColorChannelInput
          key={`${format}-${index}`}
          classes={classes}
          format={format}
          index={index}
        />
      ))}
    </div>
  );
}
