// packages/color-picker/angular/ColorSlider.ts
import { Component, Input } from '@angular/core';
import {
  sliderLabels,
  type SliderChannel,
  type ColorPartClasses,
} from '../core';
import { ColorRange } from './primitives';
@Component({
  selector: 'cp-slider',
  standalone: true,
  imports: [ColorRange],
  template: ` <label
    data-cp-part="slider"
    [attr.data-channel]="channel"
    [class]="
      'cp-slider ' +
      className +
      ' ' +
      (classes.root ?? '') +
      ' ' +
      (classes.label ?? '')
    "
  >
    {{ label || labels[channel]
    }}<input
      [cpSlider]="channel"
      [attr.aria-label]="label || labels[channel]"
      [class]="(classes.track ?? '') + ' ' + (classes.input ?? '')"
  /></label>`,
})
export class ColorSlider {
  @Input() channel: SliderChannel = 'h';
  @Input() classes: ColorPartClasses = {};
  @Input() className = '';
  @Input() label = '';
  readonly labels = sliderLabels;
}

// packages/color-picker/react/ColorSlider.tsx
'use client';
import type { ComponentProps } from 'react';
import { sliderLabels, type ColorPartClasses } from '../core';
import { ColorRange } from './primitives';
export function ColorSlider({
  channel = 'h',
  label,
  className = '',
  classes = {},
  ...attributes
}: ComponentProps<typeof ColorRange> & {
  label?: string;
  classes?: ColorPartClasses;
}) {
  return (
    <label
      className={`cp-slider ${className} ${classes.root ?? ''} ${classes.label ?? ''}`}
      data-cp-part="slider"
      data-channel={channel}
    >
      {label ?? sliderLabels[channel]}
      <ColorRange
        {...attributes}
        channel={channel}
        aria-label={label ?? sliderLabels[channel]}
        className={`${classes.track ?? ''} ${classes.input ?? ''}`}
      />
    </label>
  );
}
