// packages/color-picker/svelte/ColorArea.svelte
<script lang="ts">
  import { onMount, type Snippet } from 'svelte';
  import {
    areaStyle,
    thumbStyle,
    bindColorArea,
    type ColorPartClasses,
  } from '../core';
  import { useColor, useColorStore } from './context';
  let {
    class: className = '',
    label = 'Saturation and brightness',
    classes = {},
    style = '',
    thumbText = '',
    thumb,
  }: {
    class?: string;
    label?: string;
    classes?: ColorPartClasses;
    style?: string;
    thumbText?: string;
    thumb?: Snippet;
  } = $props();
  const store = useColorStore(),
    color = useColor();
  let element: HTMLDivElement;
  onMount(() => bindColorArea(element, store));
</script>

<!-- svelte-ignore a11y_no_noninteractive_tabindex (A two-axis keyboard surface; one-dimensional sliders are also available.) -->
<div
  bind:this={element}
  class="cp-area {className} {classes.root ?? ''}"
  data-cp-part="surface"
  role="group"
  tabindex="0"
  aria-label="{label}. Arrow keys adjust; Shift for larger steps. {Math.round(
    $color.s,
  )}% saturation, {Math.round($color.v)}% brightness."
  style={`${areaStyle($color)};${style}`}
>
  <span
    data-cp-part="thumb"
    class={classes.thumb}
    aria-hidden="true"
    style={thumbStyle($color)}
    ><span data-cp-part="thumb-text" class={classes.text}
      >{#if thumb}{@render thumb()}{:else}{thumbText}{/if}</span
    ></span
  >
</div>

// packages/color-picker/vue/ColorArea.vue
<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue';
import {
  areaStyle,
  thumbStyle,
  bindColorArea,
  type ColorPartClasses,
} from '../core';
import { useColor, useColorStore } from './context';
withDefaults(
  defineProps<{
    label?: string;
    classes?: ColorPartClasses;
    thumbText?: string;
  }>(),
  { classes: () => ({}) },
);
const store = useColorStore(),
  color = useColor(),
  element = ref<HTMLElement>();
let cleanup: (() => void) | undefined;
onMounted(() => {
  cleanup = bindColorArea(element.value!, store);
});
onBeforeUnmount(() => cleanup?.());
</script>
<template>
  <div
    ref="element"
    :class="['cp-area', classes.root]"
    data-cp-part="surface"
    role="group"
    tabindex="0"
    :aria-label="`${label ?? 'Saturation and brightness'}. Arrow keys adjust; Shift for larger steps. ${Math.round(color.s)}% saturation, ${Math.round(color.v)}% brightness.`"
    :style="areaStyle(color)"
  >
    <span
      data-cp-part="thumb"
      :class="classes.thumb"
      aria-hidden="true"
      :style="thumbStyle(color)"
      ><span data-cp-part="thumb-text" :class="classes.text"
        ><slot name="thumb">{{ thumbText }}</slot></span
      ></span
    >
  </div>
</template>
