// packages/color-picker/svelte/ColorInput.svelte
<script lang="ts">
  import type { ColorFormat } from '../core';
  import type { ColorPartClasses } from '../core';
  import { useColor } from './context';
  import ColorTextInput from './ColorTextInput.svelte';
  import ColorChannelInput from './ColorChannelInput.svelte';
  let {
    format: override,
    label,
    class: className = '',
    classes = {},
  }: {
    format?: ColorFormat;
    label?: string;
    classes?: ColorPartClasses;
    class?: string;
  } = $props();
  const color = useColor();
  const format = $derived(override ?? $color.format);
</script>

{#if format === 'hex'}<ColorTextInput
    format="hex"
    label={label ?? 'HEX'}
    class={className}
    {classes}
  />{:else}<div
    class="cp-channels {className}"
    role="group"
    aria-label={label ?? format.toUpperCase()}
  >
    {#each [0, 1, 2] as index (`${format}-${index}`)}<ColorChannelInput
        {classes}
        {format}
        index={index as 0 | 1 | 2}
      />{/each}
  </div>{/if}

// packages/color-picker/vue/ColorInput.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { ColorFormat } from '../core';
import type { ColorPartClasses } from '../core';
import { useColor } from './context';
import ColorTextInput from './ColorTextInput.vue';
import ColorChannelInput from './ColorChannelInput.vue';
const props = defineProps<{
  classes?: ColorPartClasses;
  format?: ColorFormat;
  label?: string;
}>();
const color = useColor(),
  format = computed(() => props.format ?? color.value.format);
</script>
<template>
  <ColorTextInput
    v-if="format === 'hex'"
    format="hex"
    :classes="classes"
    :label="label ?? 'HEX'"
  />
  <div
    v-else
    class="cp-channels"
    role="group"
    :aria-label="label ?? format.toUpperCase()"
  >
    <ColorChannelInput
      v-for="index in [0, 1, 2] as const"
      :key="`${format}-${index}`"
      :format="format"
      :classes="classes"
      :index="index"
    />
  </div>
</template>
