// packages/color-picker/svelte/ColorSlider.svelte
<script lang="ts">
  import {
    sliderLabels,
    sliderValue,
    setSliderValue,
    alphaTrackStyle,
    type SliderChannel,
    type ColorPartClasses,
  } from '../core';
  import { useColor, useColorStore } from './context';
  let {
    channel = 'h',
    label,
    class: className = '',
    classes = {},
  }: {
    channel?: SliderChannel;
    label?: string;
    class?: string;
    classes?: ColorPartClasses;
  } = $props();
  const store = useColorStore(),
    color = useColor();
</script>

<label
  class="cp-slider {className} {classes.root ?? ''} {classes.label ?? ''}"
  data-cp-part="slider"
  data-channel={channel}
  style={alphaTrackStyle($color.hex)}
  >{label ?? sliderLabels[channel]}<input
    data-cp-part="track"
    class="{classes.track ?? ''} {classes.input ?? ''}"
    type="range"
    min="0"
    max={channel === 'h' ? 359 : 100}
    step="1"
    value={sliderValue($color, channel)}
    oninput={(e) =>
      setSliderValue(store, channel, Number(e.currentTarget.value))}
  /></label
>

// packages/color-picker/vue/ColorSlider.vue
<script setup lang="ts">
import {
  sliderLabels,
  sliderValue,
  setSliderValue,
  alphaTrackStyle,
  type SliderChannel,
  type ColorPartClasses,
} from '../core';
import { useColor, useColorStore } from './context';
withDefaults(
  defineProps<{
    channel?: SliderChannel;
    label?: string;
    classes?: ColorPartClasses;
  }>(),
  { channel: 'h', classes: () => ({}) },
);
const store = useColorStore(),
  color = useColor();
</script>
<template>
  <label
    :class="['cp-slider', classes.root, classes.label]"
    data-cp-part="slider"
    :data-channel="channel"
    :style="alphaTrackStyle(color.hex)"
    >{{ label ?? sliderLabels[channel]
    }}<input
      data-cp-part="track"
      :class="[classes.track, classes.input]"
      type="range"
      min="0"
      :max="channel === 'h' ? 359 : 100"
      step="1"
      :value="sliderValue(color, channel)"
      @input="
        setSliderValue(
          store,
          channel,
          Number(($event.target as HTMLInputElement).value),
        )
      "
  /></label>
</template>
