// packages/color-picker/svelte/ColorRange.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from 'svelte/elements';
  import {
    bindColorSlider,
    sliderAttributes,
    sliderLabels,
    sliderTrackStyle,
    type SliderChannel,
  } from '../core';
  import { useColor, useColorStore } from './context';
  let {
    channel = 'h',
    style = '',
    disabled = false,
    ref = $bindable(),
    ...attributes
  }: Omit<HTMLInputAttributes, 'value'> & {
    channel?: SliderChannel;
    ref?: HTMLInputElement;
  } = $props();
  const store = useColorStore(),
    color = useColor();
  $effect(() => {
    if (ref) return bindColorSlider(ref, store, channel, () => !!disabled);
  });
</script>

<input
  aria-label={sliderLabels[channel]}
  {...attributes}
  {...sliderAttributes($color, channel)}
  disabled={disabled || $color.disabled}
  bind:this={ref}
  data-cp-part="slider"
  data-channel={channel}
  style={`${sliderTrackStyle($color)};${style}`}
/>

// packages/color-picker/vue/ColorRange.vue
<script setup lang="ts">
defineOptions({ inheritAttrs: false });
import { ref, watch } from 'vue';
import {
  bindColorSlider,
  sliderAttributes,
  sliderLabels,
  sliderTrackVariables,
  type SliderChannel,
} from '../core';
import { useColor, useColorStore } from './context';
const props = withDefaults(
  defineProps<{ channel?: SliderChannel; disabled?: boolean }>(),
  { channel: 'h' },
);
const state = useColor(),
  store = useColorStore(),
  element = ref<HTMLInputElement>();
watch(
  [element, () => props.channel],
  ([node], _old, cleanup) => {
    if (node)
      cleanup(
        bindColorSlider(node, store, props.channel, () => !!props.disabled),
      );
  },
  { flush: 'post' },
);
defineExpose({ element });
</script>
<template>
  <input
    :aria-label="sliderLabels[channel]"
    :style="sliderTrackVariables(state)"
    v-bind="{ ...$attrs, ...sliderAttributes(state, channel) }"
    ref="element"
    :disabled="disabled || state.disabled"
    data-cp-part="slider"
    :data-channel="channel"
  />
</template>
