// packages/color-picker/svelte/ColorProvider.svelte
<script lang="ts">
  import { onMount, untrack, type Snippet } from 'svelte';
  import {
    subscribeColor,
    createColorStore,
    type ColorView,
    type ColorStore,
  } from '../core';
  import { provideColor, useColor } from './context';
  let {
    value,
    view = 'area',
    onChange,
    children,
    disabled,
    store: provided,
  }: {
    value?: string;
    disabled?: boolean;
    view?: ColorView;
    onChange?: (hex: string) => void;
    children: Snippet;
    store?: ColorStore;
  } = $props();
  const store = provideColor(
    untrack(() => provided ?? createColorStore(value, 'hex', view, disabled)),
  );
  untrack(() => {
    if (disabled !== undefined) store.setDisabled(disabled);
  });
  const color = useColor();
  $effect(() => {
    if (disabled !== undefined) store.setDisabled(disabled);
  });
  $effect(() => {
    if (value !== undefined) store.setHex(value);
  });
  onMount(() => subscribeColor(store, (hex) => onChange?.(hex)));
</script>

<fieldset
  class="cp-provider-controls"
  disabled={$color.disabled}
  inert={$color.disabled}
  aria-disabled={$color.disabled}
  data-disabled={$color.disabled}
>
  {@render children()}
</fieldset>

// packages/color-picker/vue/ColorProvider.vue
<script setup lang="ts">
import { onMounted, watch, onBeforeUnmount } from 'vue';
import {
  subscribeColor,
  createColorStore,
  type ColorView,
  type ColorStore,
} from '../core';
import { provideColor, watchColor } from './context';
const props = withDefaults(
  defineProps<{
    value?: string;
    disabled?: boolean;
    store?: ColorStore;
    view?: ColorView;
  }>(),
  { disabled: undefined },
);
const emit = defineEmits<{ change: [hex: string] }>();
const store = provideColor(
  props.store ??
    createColorStore(props.value, 'hex', props.view, props.disabled),
);
const color = watchColor(store);
watch(
  () => props.disabled,
  (value) => {
    if (value !== undefined) store.setDisabled(value);
  },
  { immediate: true },
);
let unsubscribe: (() => void) | undefined;
onMounted(() => {
  unsubscribe = subscribeColor(store, (hex) => emit('change', hex));
});
onBeforeUnmount(() => unsubscribe?.());
watch(
  () => props.value,
  (value) => {
    if (value) store.setHex(value);
  },
);
</script>
<template>
  <fieldset
    class="cp-provider-controls"
    :disabled="color.disabled"
    :inert="color.disabled"
    :aria-disabled="color.disabled"
    :data-disabled="color.disabled"
  >
    <slot />
  </fieldset>
</template>
