// packages/color-picker/vue/ColorPlane.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import {
  surfaceStyles,
  bindColorArea,
  bindMarkerWheel,
  type ColorView,
  type ColorMarker,
  type HSV,
} from '../core';
import { useColor, useColorStore } from './context';
import { provideSurface } from './surface-context';
defineOptions({ inheritAttrs: false });
const props = withDefaults(
  defineProps<{
    view?: ColorView;
    markers?: readonly ColorMarker[];
    activeId?: string;
    onSelect?: (id: string) => void;
    onMarkerChange?: (id: string, hsv: Partial<HSV>) => void;
  }>(),
  { view: 'area' },
);
const store = useColorStore(),
  state = useColor(),
  element = ref<HTMLDivElement>();
provideSurface(computed(() => props.view));
const multi = computed(() => props.markers !== undefined);
watch(
  [element, () => props.view, multi],
  ([node], _old, cleanup) => {
    if (!node) return;
    cleanup(
      multi.value
        ? bindMarkerWheel(node, {
            getMarkers: () => props.markers ?? [],
            getActiveId: () => props.activeId ?? props.markers?.[0]?.id ?? '',
            select: (id) => props.onSelect?.(id),
            setHSV: (id, hsv) => props.onMarkerChange?.(id, hsv),
          })
        : bindColorArea(node, store, props.view),
    );
  },
  { flush: 'post' },
);
defineExpose({ element });
</script>
<template>
  <div
    role="group"
    :aria-label="
      view === 'wheel' ? 'Hue and saturation' : 'Saturation and brightness'
    "
    :style="surfaceStyles(markers ? { ...state, v: 100 } : state, view)"
    v-bind="$attrs"
    ref="element"
    data-cp-part="surface"
    :data-view="view"
    :aria-disabled="state.disabled"
    :tabindex="
      state.disabled ? -1 : (($attrs.tabindex as number | undefined) ?? 0)
    "
  >
    <slot />
  </div>
</template>

// packages/color-picker/svelte/ColorPlane.svelte
<script lang="ts">
  import { untrack, type Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';
  import {
    surfaceStyles,
    styleText,
    bindColorArea,
    bindMarkerWheel,
    type ColorView,
    type ColorMarker,
    type HSV,
  } from '../core';
  import { useColor, useColorStore } from './context';
  import { provideSurface } from './surface-context';
  let {
    view = 'area',
    markers,
    activeId,
    onSelect,
    onMarkerChange,
    children,
    style = '',
    ref = $bindable(),
    ...attributes
  }: HTMLAttributes<HTMLDivElement> & {
    view?: ColorView;
    markers?: readonly ColorMarker[];
    activeId?: string;
    onSelect?: (id: string) => void;
    onMarkerChange?: (id: string, hsv: Partial<HSV>) => void;
    children?: Snippet;
    ref?: HTMLDivElement;
  } = $props();
  const store = useColorStore(),
    color = useColor();
  provideSurface(() => view);
  const multi = $derived(markers !== undefined);
  $effect(() => {
    if (!ref) return;
    const node = ref,
      currentView = view,
      isMulti = multi;
    return untrack(() => {
      return isMulti
        ? bindMarkerWheel(node, {
            getMarkers: () => markers ?? [],
            getActiveId: () => activeId ?? markers?.[0]?.id ?? '',
            select: (id) => onSelect?.(id),
            setHSV: (id, hsv) => onMarkerChange?.(id, hsv),
          })
        : bindColorArea(node, store, currentView);
    });
  });
</script>

<!-- svelte-ignore a11y_no_noninteractive_tabindex (Two-axis keyboard surface, with native sliders available.) -->
<div
  role="group"
  aria-label={view === 'wheel'
    ? 'Hue and saturation'
    : 'Saturation and brightness'}
  {...attributes}
  bind:this={ref}
  data-cp-part="surface"
  data-view={view}
  aria-disabled={$color.disabled}
  tabindex={$color.disabled ? -1 : (attributes.tabindex ?? 0)}
  style={`${styleText(surfaceStyles(markers ? { ...$color, v: 100 } : $color, view))};${style}`}
>
  {#if children}{@render children()}{/if}
</div>
