// packages/color-picker/vue/ColorField.vue
<script setup lang="ts">
defineOptions({ inheritAttrs: false });
import { ref, watch, computed } from 'vue';
import {
  bindColorValueInput,
  colorInputAttributes,
  type ColorInputOptions,
} from '../core';
import { useColor, useColorStore } from './context';
const props = defineProps<ColorInputOptions & { disabled?: boolean }>(),
  state = useColor(),
  store = useColorStore(),
  element = ref<HTMLInputElement>();
const initialValue = colorInputAttributes(store.getSnapshot(), props).value;
const inputAttrs = computed(() => {
  const { value, ...attrs } = colorInputAttributes(state.value, props);
  return attrs;
});
const vInitialValue = {
  getSSRProps: (binding: { value: string }) => ({ value: binding.value }),
};
watch(
  [element, () => props.format, () => props.index],
  ([node], _old, cleanup) => {
    if (node)
      cleanup(bindColorValueInput(node, store, props, () => !!props.disabled));
  },
  { flush: 'post' },
);
defineExpose({ element });
</script>
<template>
  <input
    v-initial-value="initialValue"
    v-bind="{ ...inputAttrs, ...$attrs }"
    ref="element"
    :disabled="disabled || state.disabled"
    data-cp-part="input"
    spellcheck="false"
  />
</template>

// packages/color-picker/svelte/ColorField.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import type { HTMLInputAttributes } from 'svelte/elements';
  import {
    bindColorValueInput,
    colorInputAttributes,
    type ColorInputOptions,
  } from '../core';
  import { useColor, useColorStore } from './context';
  let {
    format,
    index,
    disabled = false,
    ref = $bindable(),
    ...attributes
  }: Omit<HTMLInputAttributes, 'value'> &
    ColorInputOptions & { ref?: HTMLInputElement } = $props();
  const store = useColorStore(),
    color = useColor();
  const initial = untrack(
    () => colorInputAttributes(store.getSnapshot(), { format, index }).value,
  );
  const inputAttributes = $derived.by(() => {
    const { value, ...rest } = colorInputAttributes($color, { format, index });
    return rest;
  });
  $effect(() => {
    if (ref)
      return bindColorValueInput(
        ref,
        store,
        { format, index },
        () => !!disabled,
      );
  });
</script>

<input
  {...inputAttributes}
  {...attributes}
  value={initial}
  disabled={disabled || $color.disabled}
  bind:this={ref}
  data-cp-part="input"
  spellcheck="false"
/>
