// packages/color-picker/vue/ColorFormatTrigger.vue
<script setup lang="ts">
defineOptions({ inheritAttrs: false });
import { ref } from 'vue';
import { nextColorFormat, type ColorFormat } from '../core';
import { useColor, useColorStore } from './context';
const props = defineProps<{ format?: ColorFormat; disabled?: boolean }>(),
  state = useColor(),
  store = useColorStore(),
  element = ref<HTMLButtonElement>();
defineExpose({ element });
</script>
<template>
  <button
    type="button"
    aria-label="Change color format"
    v-bind="$attrs"
    ref="element"
    :disabled="disabled || state.disabled"
    data-cp-part="format-trigger"
    :aria-pressed="format ? state.format === format : undefined"
    @click="
      (event) => {
        if (!event.defaultPrevented) nextColorFormat(store, format);
      }
    "
  >
    <slot :state="state">{{ state.format.toUpperCase() }}</slot>
  </button>
</template>

// packages/color-picker/svelte/ColorFormatTrigger.svelte
<script lang="ts">
  import type { HTMLButtonAttributes } from 'svelte/elements';
  import type { Snippet } from 'svelte';
  import {
    nextColorFormat,
    type ColorFormat,
    type ColorSnapshot,
  } from '../core';
  import { useColor, useColorStore } from './context';
  let {
    format,
    children,
    onclick,
    disabled = false,
    ref = $bindable(),
    ...attributes
  }: Omit<HTMLButtonAttributes, 'children'> & {
    format?: ColorFormat;
    children?: Snippet<[ColorSnapshot]>;
    ref?: HTMLButtonElement;
  } = $props();
  const store = useColorStore(),
    color = useColor();
</script>

<button
  type="button"
  aria-label="Change color format"
  {...attributes}
  bind:this={ref}
  disabled={disabled || $color.disabled}
  data-cp-part="format-trigger"
  aria-pressed={format ? $color.format === format : undefined}
  onclick={(event) => {
    onclick?.(event);
    if (!event.defaultPrevented) nextColorFormat(store, format);
  }}
>
  {#if children}{@render children(
      $color,
    )}{:else}{$color.format.toUpperCase()}{/if}
</button>
