// packages/color-picker/vue/ColorCollection.vue
<script setup lang="ts">
import { shallowRef, watchEffect, onScopeDispose } from 'vue';
import type { ColorCollectionStore, ColorCollectionClasses } from '../core';
import { useColor } from './context';
import ColorSwatch from './ColorSwatch.vue';
const props = withDefaults(
  defineProps<{
    collection: ColorCollectionStore;
    kind?: 'recent' | 'favorites';
    label?: string;
    classes?: ColorCollectionClasses;
  }>(),
  { kind: 'recent', label: 'Recent colors' },
);
const color = useColor(),
  state = shallowRef(props.collection.getSnapshot());
watchEffect((onCleanup) => {
  state.value = props.collection.getSnapshot();
  onCleanup(
    props.collection.subscribe(
      () => (state.value = props.collection.getSnapshot()),
    ),
  );
});
</script>
<template>
  <fieldset
    :class="['cp-collection', classes?.root]"
    :disabled="color.disabled"
  >
    <legend :class="classes?.label">{{ label }}</legend>
    <span v-for="value in state[kind]" :key="value" :class="classes?.item"
      ><ColorSwatch :value="value" :label="value"
    /></span>
  </fieldset>
</template>

// packages/color-picker/svelte/ColorCollection.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import {
    type ColorCollectionStore,
    type ColorCollectionClasses,
  } from '../core';
  import { useColor } from './context';
  import ColorSwatch from './ColorSwatch.svelte';
  let {
    collection,
    kind = 'recent',
    label = 'Recent colors',
    classes = {},
  }: {
    collection: ColorCollectionStore;
    kind?: 'recent' | 'favorites';
    label?: string;
    classes?: ColorCollectionClasses;
  } = $props();
  const color = useColor();
  let state = $state(untrack(() => collection.getSnapshot()));
  $effect(() => {
    const current = collection;
    state = current.getSnapshot();
    return current.subscribe(() => (state = current.getSnapshot()));
  });
</script>

<fieldset class="cp-collection {classes.root ?? ''}" disabled={$color.disabled}>
  <legend class={classes.label}>{label}</legend>
  {#each state[kind] as value (value)}<span class={classes.item}
      ><ColorSwatch {value} label={value} /></span
    >{/each}
</fieldset>
