// packages/color-picker/react/ColorProvider.tsx
'use client';
import {
  useEffect,
  useRef,
  useState,
  useSyncExternalStore,
  type ReactNode,
} from 'react';
import {
  createColorStore,
  subscribeColor,
  type ColorStore,
  type ColorView,
} from '../core';
import { Context } from './context';
export function ColorProvider({
  value,
  view = 'area',
  onChange,
  children,
  disabled,
  store: provided,
}: {
  value?: string;
  disabled?: boolean;
  view?: ColorView;
  onChange?: (hex: string) => void;
  children: ReactNode;
  store?: ColorStore;
}) {
  const [store] = useState(() => {
    const initial = provided ?? createColorStore(value, 'hex', view, disabled);
    if (disabled !== undefined) initial.setDisabled(disabled);
    return initial;
  });
  const state = useSyncExternalStore(
    store.subscribe,
    store.getSnapshot,
    store.getServerSnapshot,
  );
  useEffect(() => {
    if (disabled !== undefined) store.setDisabled(disabled);
  }, [store, disabled]);
  const callback = useRef(onChange);
  callback.current = onChange;
  useEffect(() => {
    if (value !== undefined) store.setHex(value);
  }, [store, value]);
  useEffect(
    () => subscribeColor(store, (hex) => callback.current?.(hex)),
    [store],
  );
  return (
    <Context.Provider value={store}>
      <fieldset
        className="cp-provider-controls"
        disabled={state.disabled}
        {...(state.disabled ? { inert: '' } : {})}
        aria-disabled={state.disabled}
        data-disabled={state.disabled}
      >
        {children}
      </fieldset>
    </Context.Provider>
  );
}

// packages/color-picker/svelte/ColorProvider.svelte
<script lang="ts">
  import { onMount, untrack, type Snippet } from 'svelte';
  import {
    subscribeColor,
    createColorStore,
    type ColorView,
    type ColorStore,
  } from '../core';
  import { provideColor, useColor } from './context';
  let {
    value,
    view = 'area',
    onChange,
    children,
    disabled,
    store: provided,
  }: {
    value?: string;
    disabled?: boolean;
    view?: ColorView;
    onChange?: (hex: string) => void;
    children: Snippet;
    store?: ColorStore;
  } = $props();
  const store = provideColor(
    untrack(() => provided ?? createColorStore(value, 'hex', view, disabled)),
  );
  untrack(() => {
    if (disabled !== undefined) store.setDisabled(disabled);
  });
  const color = useColor();
  $effect(() => {
    if (disabled !== undefined) store.setDisabled(disabled);
  });
  $effect(() => {
    if (value !== undefined) store.setHex(value);
  });
  onMount(() => subscribeColor(store, (hex) => onChange?.(hex)));
</script>

<fieldset
  class="cp-provider-controls"
  disabled={$color.disabled}
  inert={$color.disabled}
  aria-disabled={$color.disabled}
  data-disabled={$color.disabled}
>
  {@render children()}
</fieldset>
