// packages/color-picker/react/ColorArea.tsx
'use client';
import type { ReactNode } from 'react';
import type { ColorPartClasses, ColorSnapshot } from '../core';
import { useColor } from './context';
import { ColorPlane, ColorThumb, type ColorPlaneProps } from './primitives';
export function ColorArea({
  className = '',
  classes = {},
  thumbText,
  renderThumb,
  label = 'Saturation and brightness',
  style,
  ...attributes
}: Omit<ColorPlaneProps, 'view'> & {
  classes?: ColorPartClasses;
  thumbText?: ReactNode;
  renderThumb?: (state: ColorSnapshot) => ReactNode;
  label?: string;
}) {
  const state = useColor();
  return (
    <ColorPlane
      {...attributes}
      className={`cp-area ${className} ${classes.root ?? ''}`}
      aria-label={label}
      style={{
        width: '100%',
        minHeight: 'var(--cp-area-height,180px)',
        ...style,
      }}
    >
      <ColorThumb className={`cp-thumb ${classes.thumb ?? ''}`}>
        <span data-cp-part="thumb-text" className={classes.text}>
          {renderThumb ? renderThumb(state) : thumbText}
        </span>
      </ColorThumb>
    </ColorPlane>
  );
}

// packages/color-picker/svelte/ColorArea.svelte
<script lang="ts">
  import type { ComponentProps, Snippet } from 'svelte';
  import type { ColorPartClasses } from '../core';
  import ColorPlane from './ColorPlane.svelte';
  import ColorThumb from './ColorThumb.svelte';
  let {
    class: className = '',
    classes = {},
    style = '',
    thumbText = '',
    thumb,
    label = 'Saturation and brightness',
    ...attributes
  }: Omit<ComponentProps<typeof ColorPlane>, 'view'> & {
    classes?: ColorPartClasses;
    thumbText?: string;
    thumb?: Snippet;
    label?: string;
  } = $props();
</script>

<ColorPlane
  {...attributes}
  class="cp-area {className} {classes.root ?? ''}"
  aria-label={label}
  style={`width:100%;min-height:var(--cp-area-height,180px);${style}`}
>
  <ColorThumb class="cp-thumb {classes.thumb ?? ''}"
    ><span data-cp-part="thumb-text" class={classes.text}
      >{#if thumb}{@render thumb()}{:else}{thumbText}{/if}</span
    ></ColorThumb
  >
</ColorPlane>
