// packages/color-picker/react/ColorInput.tsx
'use client';
import { type ColorFormat, type ColorPartClasses } from '../core';
import { ColorChannelInput } from './ColorChannelInput';
import { ColorTextInput } from './ColorTextInput';
import { useColor } from './context';
export function ColorInput({
  format: override,
  label,
  className = '',
  classes = {},
}: {
  format?: ColorFormat;
  label?: string;
  className?: string;
  classes?: ColorPartClasses;
}) {
  const state = useColor(),
    format = override ?? state.format;
  return format === 'hex' ? (
    <ColorTextInput
      format="hex"
      label={label ?? 'HEX'}
      className={className}
      classes={classes}
    />
  ) : (
    <div
      className={`cp-channels ${className}`}
      role="group"
      aria-label={label ?? format.toUpperCase()}
    >
      {([0, 1, 2] as const).map((index) => (
        <ColorChannelInput
          key={`${format}-${index}`}
          classes={classes}
          format={format}
          index={index}
        />
      ))}
    </div>
  );
}

// packages/color-picker/svelte/ColorInput.svelte
<script lang="ts">
  import type { ColorFormat } from '../core';
  import type { ColorPartClasses } from '../core';
  import { useColor } from './context';
  import ColorTextInput from './ColorTextInput.svelte';
  import ColorChannelInput from './ColorChannelInput.svelte';
  let {
    format: override,
    label,
    class: className = '',
    classes = {},
  }: {
    format?: ColorFormat;
    label?: string;
    classes?: ColorPartClasses;
    class?: string;
  } = $props();
  const color = useColor();
  const format = $derived(override ?? $color.format);
</script>

{#if format === 'hex'}<ColorTextInput
    format="hex"
    label={label ?? 'HEX'}
    class={className}
    {classes}
  />{:else}<div
    class="cp-channels {className}"
    role="group"
    aria-label={label ?? format.toUpperCase()}
  >
    {#each [0, 1, 2] as index (`${format}-${index}`)}<ColorChannelInput
        {classes}
        {format}
        index={index as 0 | 1 | 2}
      />{/each}
  </div>{/if}
